org: shinryuzz
app: sample-01
service: serverless-fw-express-sample
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: "ap-northeast-1"
  stage: "dev"

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: "node20"
    define: { "rezuire.resolve": undefined }
    platform: "node"
    concurrency: 10
    watch:
      pattern: "src/**/*.ts" # match only typescript files in src directory
      ignore: "temp/**/*"

functions:
  api:
    handler: src/handler.handler
    events:
      - http:
          method: any
          path: "/"
          cors: true
      - http:
          method: any
          path: "/{any+}"
          cors: true

plugins:
  - serverless-esbuild
  - serverless-offline
